users:
  hellagood9:
    username: hellagood9
    articleIds:
      - 1
      - 2
    commentIds:
      - 1
  ralph99:
    username: ralph99
    articleIds: []
    commentIds:
      - 2
  revenant89:
    username: revenant89
    articleIds:
      - 3
    commentIds: []
articles:
  '1':
    id: 1
    title: 'The difference between ForEach, and For…In'
    url: >-
      https://codeburst.io/javascript-the-difference-between-foreach-and-for-in-992db038e4c2
    username: hellagood9
    commentIds:
      - 1
    upvotedBy:
      - hellagood9
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: An Introduction to Regular Expressions (Regex) In JavaScript
    url: >-
      https://codeburst.io/an-introduction-to-regular-expressions-regex-in-javascript-1d3559e7ac9a
    username: hellagood9
    commentIds:
      - 2
    upvotedBy: []
    downvotedBy:
      - hellagood9
      - ralph99
    comments: []
  '3':
    id: 3
    title: 19+ JavaScript Shorthand Coding Techniques
    url: 'https://www.sitepoint.com/shorthand-javascript-techniques/'
    username: revenant89
    commentIds: []
    upvotedBy:
      - hellagood9
    downvotedBy: []
nextArticleId: 4
comments:
  '1':
    id: 1
    body: Great article!!! Thanks for sharing.
    username: hellagood9
    articleId: 1
    upvotedBy:
      - hellagood9
    downvotedBy: []
  '2':
    id: 2
    body: I did not like it!
    username: ralph99
    articleId: 2
    upvotedBy: []
    downvotedBy:
      - hellagood9
nextCommentId: 3
